[package]
name = "athenisa-dis"
version.workspace = true
edition.workspace = true
description = "Disassembler for the AthenISA instruction set"
readme = "README.md"
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
athenisa-isa.workspace = true
