[workspace]
members = [
    "isa",
    "assembler",
    "disassembler",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/morsoth/athenisa"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
athenisa-isa = { path = "isa" }
